import { useState } from "react";

import InputArea from "./Chat/InputArea";
import Sidebar from "./Chat/Sidebar";
import MessagesArea from "./Chat/MessageArea";
import ChatHeader from "./Chat/Header";
import type { Session } from "./Chat/SessionItem";
import type { Message } from "./Chat/MessageBubble";

export default function Chat() {
  const [sessions, setSessions] = useState<Session[]>([
    { id: 1, title: "New Chat", messages: [], createdAt: new Date() },
  ]);
  const [currentSessionId, setCurrentSessionId] = useState(1);
  const [inputMessage, setInputMessage] = useState("");
  const [sidebarOpen, setSidebarOpen] = useState(true);

  const currentSession = sessions.find((s) => s.id === currentSessionId);

  const handleSendMessage = () => {
    if (!inputMessage.trim()) return;
    const newMessage: Message = {
      // Add type annotation here
      id: Date.now(),
      text: inputMessage,
      sender: "user" as const, // or add 'as const'
      timestamp: new Date(),
    };
    setSessions(
      sessions.map((session) => {
        if (session.id === currentSessionId) {
          const updatedMessages = [...session.messages, newMessage];
          setTimeout(() => {
            const aiResponse: Message = {
              // Add type annotation here
              id: Date.now() + 1,
              text: "This is a simulated AI response. In a real application, this would be generated by your AI model.",
              sender: "ai" as const, // or add 'as const'
              timestamp: new Date(),
            };
            setSessions((prev) =>
              prev.map((s) =>
                s.id === currentSessionId
                  ? { ...s, messages: [...s.messages, aiResponse] }
                  : s,
              ),
            );
          }, 500);
          const title =
            session.messages.length === 0
              ? inputMessage.slice(0, 30) +
                (inputMessage.length > 30 ? "..." : "")
              : session.title;
          return { ...session, messages: updatedMessages, title };
        }
        return session;
      }),
    );
    setInputMessage("");
  };

  const handleNewChat = () => {
    const newSession = {
      id: Date.now(),
      title: "New Chat",
      messages: [],
      createdAt: new Date(),
    };
    setSessions([newSession, ...sessions]);
    setCurrentSessionId(newSession.id);
  };

  const handleDeleteSession = (sessionId: number): void => {
    if (sessions.length === 1) {
      const newSessionId = Date.now();
      setSessions([
        {
          id: newSessionId,
          title: "New Chat",
          messages: [],
          createdAt: new Date(),
        },
      ]);
      setCurrentSessionId(newSessionId);
    } else {
      setSessions(sessions.filter((s) => s.id !== sessionId));
      if (currentSessionId === sessionId) {
        const nextSession = sessions.find((s) => s.id !== sessionId);
        if (nextSession) {
          setCurrentSessionId(nextSession.id);
        }
      }
    }
  };

  const handleRenameSession = (sessionId: number, newTitle: string): void => {
    setSessions(
      sessions.map((s) => (s.id === sessionId ? { ...s, title: newTitle } : s)),
    );
  };

  return (
    <div className="flex h-screen" style={{ backgroundColor: "#F6EFD2" }}>
      <Sidebar
        isOpen={sidebarOpen}
        sessions={sessions}
        currentSessionId={currentSessionId}
        onNewChat={handleNewChat}
        onSelectSession={setCurrentSessionId}
        onRenameSession={handleRenameSession}
        onDeleteSession={handleDeleteSession}
      />

      <div className="flex-1 flex flex-col">
        <ChatHeader
          title={currentSession?.title}
          sidebarOpen={sidebarOpen}
          onToggleSidebar={() => setSidebarOpen(!sidebarOpen)}
        />

        <div className="flex-1 overflow-y-auto px-4 py-6">
          <MessagesArea messages={currentSession?.messages || []} />
        </div>

        <InputArea
          value={inputMessage}
          onChange={setInputMessage}
          onSend={handleSendMessage}
        />
      </div>
    </div>
  );
}
