import { useState } from "react";

import Sidebar from "./Chat/Sidebar";
import ChatHeader from "./Chat/Header";
import MessagesArea from "./Chat/MessageArea";
import InputArea from "./Chat/InputArea";

export interface Message {
  id: number;
  text: string;
  sender: "user" | "ai";
  timestamp: Date;
}

export interface Session {
  id: number;
  title: string;
  messages: Message[];
  createdAt: Date;
}

export default function Chat() {
  const [sessions, setSessions] = useState<Session[]>([
    { id: 1, title: "New Chat", messages: [], createdAt: new Date() },
  ]);
  const [currentSessionId, setCurrentSessionId] = useState<number>(1);
  const [inputMessage, setInputMessage] = useState<string>("");
  const [sidebarOpen, setSidebarOpen] = useState<boolean>(true);

  const currentSession = sessions.find((s) => s.id === currentSessionId);

  const handleSendMessage = () => {
    if (!inputMessage.trim()) return;

    const newMessage: Message = {
      id: Date.now(),
      text: inputMessage,
      sender: "user",
      timestamp: new Date(),
    };

    setSessions(
      sessions.map((session) => {
        if (session.id === currentSessionId) {
          const updatedMessages = [...session.messages, newMessage];

          setTimeout(() => {
            const aiResponse: Message = {
              id: Date.now() + 1,
              text: "This is a simulated AI response. In a real application, this would be generated by your AI model.",
              sender: "ai",
              timestamp: new Date(),
            };

            setSessions((prev) =>
              prev.map((s) =>
                s.id === currentSessionId
                  ? { ...s, messages: [...s.messages, aiResponse] }
                  : s,
              ),
            );
          }, 500);

          const title =
            session.messages.length === 0
              ? inputMessage.slice(0, 30) +
                (inputMessage.length > 30 ? "..." : "")
              : session.title;

          return { ...session, messages: updatedMessages, title };
        }
        return session;
      }),
    );

    setInputMessage("");
  };

  const handleNewChat = () => {
    const newSession: Session = {
      id: Date.now(),
      title: "New Chat",
      messages: [],
      createdAt: new Date(),
    };
    setSessions([newSession, ...sessions]);
    setCurrentSessionId(newSession.id);
  };

  const handleDeleteSession = (sessionId: number) => {
    if (sessions.length === 1) {
      const newSessionId = Date.now();
      setSessions([
        {
          id: newSessionId,
          title: "New Chat",
          messages: [],
          createdAt: new Date(),
        },
      ]);
      setCurrentSessionId(newSessionId);
    } else {
      setSessions(sessions.filter((s) => s.id !== sessionId));
      if (currentSessionId === sessionId) {
        const nextSession = sessions.find((s) => s.id !== sessionId);
        if (nextSession) {
          setCurrentSessionId(nextSession.id);
        }
      }
    }
  };

  const handleRenameSession = (sessionId: number, newTitle: string) => {
    setSessions(
      sessions.map((s) => (s.id === sessionId ? { ...s, title: newTitle } : s)),
    );
  };

  return (
    <div className="flex h-screen bg-gray-100">
      <Sidebar
        isOpen={sidebarOpen}
        sessions={sessions}
        currentSessionId={currentSessionId}
        onNewChat={handleNewChat}
        onSelectSession={setCurrentSessionId}
        onRenameSession={handleRenameSession}
        onDeleteSession={handleDeleteSession}
      />

      <div className="flex-1 flex flex-col">
        <ChatHeader
          title={currentSession?.title}
          sidebarOpen={sidebarOpen}
          onToggleSidebar={() => setSidebarOpen(!sidebarOpen)}
        />

        <div className="flex-1 overflow-y-auto px-4 py-6">
          <MessagesArea messages={currentSession?.messages || []} />
        </div>

        <InputArea
          value={inputMessage}
          onChange={setInputMessage}
          onSend={handleSendMessage}
        />
      </div>
    </div>
  );
}
